version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      # Refresh yum metadata
      #- yum clean all
      #- yum update -y

      # Install Development Tools (gcc, make, etc.)
      #- yum groupinstall -y "Development Tools"

      - pip install -r aws/gatewayapi_requirements.txt -t .
  build:
    commands:
      # Copy Lambda source code into root of build directory
      - cp aws/*.py .

artifacts:
  files:
    - '**/*.py'
  #base-directory: package
